#pragma once
#include "OsDeclarations.h"
#include "Susi4.h"
#ifdef __cplusplus
extern "C" {
#endif
#define SUSI_ID_BASE_GET_NAME_X86_NV_AI					(0xA0000000)
#define SUSI_ID_BASE_GET_NAME_ARM_NV_AI					(0xB0000000)
#define SUSI_ID_BASE_GET_NAME_DOCKER_IMG_AI				(0xC0000000)
#define SUSI_ID_BASE_GET_NAME_CONTAINER_AI				(0xD0000000)
#define SUSI_ID_BASE_GET_NAME_X86_INTEL_AI				(0xE0000000)
#define SUSI_ID_BASE_GET_NAME_ARM_MTK_AI				(0xF0000000)
#define SUSI_ID_BASE_GET_NAME_ARM_NXP_AI				(0xF0000001)

#define SUSI_ID_MAPPING_GET_NAME_X86_NV_AI(Id)			((SusiId_t)(Id | SUSI_ID_BASE_GET_NAME_X86_NV_AI))
#define SUSI_ID_MAPPING_GET_NAME_X86_INTEL_AI(Id)		((SusiId_t)(Id | SUSI_ID_BASE_GET_NAME_X86_INTEL_AI))
#define SUSI_ID_MAPPING_GET_NAME_ARM_NV_AI(Id)			((SusiId_t)(Id | SUSI_ID_BASE_GET_NAME_ARM_NV_AI))
#define SUSI_ID_MAPPING_GET_NAME_DOCKER_IMG_AI(Id)		((SusiId_t)(Id | SUSI_ID_BASE_GET_NAME_DOCKER_IMG_AI))
#define SUSI_ID_MAPPING_GET_NAME_CONTAINER_AI(Id)		((SusiId_t)(Id | SUSI_ID_BASE_GET_NAME_CONTAINER_AI))
#define SUSI_ID_MAPPING_GET_NAME_ARM_MTK_AI(Id)			((SusiId_t)(Id | SUSI_ID_BASE_GET_NAME_ARM_MTK_AI))
#define SUSI_ID_MAPPING_GET_NAME_ARM_NXP_AI(Id)			((SusiId_t)(Id | SUSI_ID_BASE_GET_NAME_ARM_NXP_AI))

#define SUSI_ID_MAPPING_GET_VALUE(Id, index)			((SusiId_t)(Id | (index << 20)))
#define SUSI_ID_MAPPING_GET_ITEM(Id)					((SusiId_t)(Id & 0xF00FFFFF))

//X86 nvidia-smi(ubuntu)
#define SUSI_AI_ID_X86_NV_MAX					12
#define SUSI_AI_ID_X86_NV_BASE					0x00026000
#define SUSI_AI_ID_X86_NV_SN					((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x0))
#define SUSI_AI_ID_X86_NV_VOLATILE_UTILITY		((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x1))
#define SUSI_AI_ID_X86_NV_TEMP					((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x2))
#define SUSI_AI_ID_X86_NV_PERF					((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x3))
#define SUSI_AI_ID_X86_NV_POWER_USAGE			((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x4))
#define SUSI_AI_ID_X86_NV_POWER_CAP				((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x5))
#define SUSI_AI_ID_X86_NV_MEM_INUSE				((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x6))
#define SUSI_AI_ID_X86_NV_MEM_TOTAL				((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x7))
#define SUSI_AI_ID_X86_NV_FAN_SPEED				((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x8))
#define	SUSI_AI_ID_X86_NV_GET_COUNT				((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0x9))
#define	SUSI_AI_ID_X86_NV_COMPUTE_MODE			((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0xA))
#define	SUSI_AI_ID_X86_NV_DISPLAY_ACTIVE		((SusiId_t)(SUSI_AI_ID_X86_NV_BASE + 0xB))

#define SUSI_AI_ID_X86_NV_STR_MAX				4
#define SUSI_AI_ID_X86_NV_NAME_STR				((SusiId_t)(SUSI_ID_BASE_GET_NAME_X86_NV_AI + 0x0))
#define SUSI_AI_ID_X86_NV_DRIVER_VERSION_STR	((SusiId_t)(SUSI_ID_BASE_GET_NAME_X86_NV_AI + 0x1))
#define SUSI_AI_ID_X86_NV_CUDA_VERSION_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_X86_NV_AI + 0x2))
#define SUSI_AI_ID_X86_NV_CUDNN_VERSION_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_X86_NV_AI + 0x3))

//Docker image and container statistics
#define SUSI_AI_ID_DOCKER_COMMON_MAX			4
#define SUSI_AI_ID_DOCKER_COMMON_BASE			0x00027000
#define SUSI_AI_ID_DOCKER_IMG_COUNT				((SusiId_t)(SUSI_AI_ID_DOCKER_COMMON_BASE + 0x0))
#define SUSI_AI_ID_CONTAINER_COUNT				((SusiId_t)(SUSI_AI_ID_DOCKER_COMMON_BASE + 0x1))
#define SUSI_AI_ID_CONTAINER_RUN_COUNT			((SusiId_t)(SUSI_AI_ID_DOCKER_COMMON_BASE + 0x2))
#define SUSI_AI_ID_CONTAINER_PAUSE_COUNT		((SusiId_t)(SUSI_AI_ID_DOCKER_COMMON_BASE + 0x3))

//Docker image
#define SUSI_AI_ID_DOCKER_IMG_MAX				1
#define SUSI_AI_ID_DOCKER_IMG_BASE				0x00028000
#define SUSI_AI_ID_DOCKER_IMG_SIZE				((SusiId_t)(SUSI_AI_ID_DOCKER_IMG_BASE + 0x0))

#define SUSI_AI_ID_DOCKER_IMG_STR_MAX			6
#define SUSI_AI_ID_DOCKER_IMG_ID_STR			((SusiId_t)(SUSI_ID_BASE_GET_NAME_DOCKER_IMG_AI + 0x0))
#define SUSI_AI_ID_DOCKER_IMG_TAG_STR			((SusiId_t)(SUSI_ID_BASE_GET_NAME_DOCKER_IMG_AI + 0x1))
#define SUSI_AI_ID_DOCKER_IMG_OS_STR			((SusiId_t)(SUSI_ID_BASE_GET_NAME_DOCKER_IMG_AI + 0x2))
#define SUSI_AI_ID_DOCKER_IMG_ARCHITECTURE_STR	((SusiId_t)(SUSI_ID_BASE_GET_NAME_DOCKER_IMG_AI + 0x3))
#define SUSI_AI_ID_DOCKER_IMG_BUILD_TIME_STR	((SusiId_t)(SUSI_ID_BASE_GET_NAME_DOCKER_IMG_AI + 0x4))
#define SUSI_AI_ID_DOCKER_IMG_BUILD_VER_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_DOCKER_IMG_AI + 0x5))

//Container
#define SUSI_AI_ID_CONTAINER_MAX				4
#define SUSI_AI_ID_CONTAINER_BASE				0x00029000
#define SUSI_AI_ID_CONTAINER_CPU_USAGE			((SusiId_t)(SUSI_AI_ID_CONTAINER_BASE + 0x0))
#define SUSI_AI_ID_CONTAINER_MEM_USAGE			((SusiId_t)(SUSI_AI_ID_CONTAINER_BASE + 0x1))
#define SUSI_AI_ID_CONTAINER_MEM_INUSE			((SusiId_t)(SUSI_AI_ID_CONTAINER_BASE + 0x2))
#define SUSI_AI_ID_CONTAINER_MEM_TOTAL			((SusiId_t)(SUSI_AI_ID_CONTAINER_BASE + 0x3))

#define SUSI_AI_ID_CONTAINER_STR_MAX			8
#define SUSI_AI_ID_CONTAINER_RUN_ON_IMG_ID_STR	((SusiId_t)(SUSI_ID_BASE_GET_NAME_CONTAINER_AI + 0x0))
#define SUSI_AI_ID_CONTAINER_RUN_ON_IMG_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_CONTAINER_AI + 0x1))
#define SUSI_AI_ID_CONTAINER_NAME_STR			((SusiId_t)(SUSI_ID_BASE_GET_NAME_CONTAINER_AI + 0x2))
#define SUSI_AI_ID_CONTAINER_ID_STR				((SusiId_t)(SUSI_ID_BASE_GET_NAME_CONTAINER_AI + 0x3))
#define SUSI_AI_ID_CONTAINER_STATUS_STR			((SusiId_t)(SUSI_ID_BASE_GET_NAME_CONTAINER_AI + 0x4))
#define SUSI_AI_ID_CONTAINER_CONN_IP_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_CONTAINER_AI + 0x5))
#define SUSI_AI_ID_CONTAINER_CONN_GATEWAY_STR	((SusiId_t)(SUSI_ID_BASE_GET_NAME_CONTAINER_AI + 0x6))
#define SUSI_AI_ID_CONTAINER_CONN_MAC_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_CONTAINER_AI + 0x7))

//jetson
#define SUSI_AI_ID_ARM_NV_MAX					6
#define SUSI_AI_ID_ARM_NV_BASE					0x0002A000
#define SUSI_AI_ID_ARM_NV_CPU_USAGE				((SusiId_t)(SUSI_AI_ID_ARM_NV_BASE + 0x0))
#define SUSI_AI_ID_ARM_NV_GPU_USAGE				((SusiId_t)(SUSI_AI_ID_ARM_NV_BASE + 0x1))
#define SUSI_AI_ID_ARM_NV_TEMP					((SusiId_t)(SUSI_AI_ID_ARM_NV_BASE + 0x2))
#define SUSI_AI_ID_ARM_NV_RAM_USAGE				((SusiId_t)(SUSI_AI_ID_ARM_NV_BASE + 0x3))
#define SUSI_AI_ID_ARM_NV_FAN_SPEED				((SusiId_t)(SUSI_AI_ID_ARM_NV_BASE + 0x4))
#define SUSI_AI_ID_ARM_NV_POWER_MODE_Total		((SusiId_t)(SUSI_AI_ID_ARM_NV_BASE + 0x5))

#define SUSI_AI_ID_ARM_NV_STR_MAX				8
#define SUSI_AI_ID_ARM_NV_CUDA_VERSION_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_ARM_NV_AI + 0x0))
#define SUSI_AI_ID_ARM_NV_CUDNN_VERSION_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_ARM_NV_AI + 0x1))
#define SUSI_AI_ID_ARM_NV_TENSORRT_VERSION_STR	((SusiId_t)(SUSI_ID_BASE_GET_NAME_ARM_NV_AI + 0x2))
#define SUSI_AI_ID_ARM_NV_OPENCV_VERSION_STR	((SusiId_t)(SUSI_ID_BASE_GET_NAME_ARM_NV_AI + 0x3))
#define SUSI_AI_ID_ARM_NV_HW_VERSION_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_ARM_NV_AI + 0x4))
#define SUSI_AI_ID_ARM_NV_PW_MODE_STR			((SusiId_t)(SUSI_ID_BASE_GET_NAME_ARM_NV_AI + 0x5))
#define SUSI_AI_ID_ARM_NV_JETPACK_INFO_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_ARM_NV_AI + 0x6))
#define SUSI_AI_ID_ARM_NV_POWER_MODE_NAME		((SusiId_t)(SUSI_ID_BASE_GET_NAME_ARM_NV_AI + 0x7))

#define SUSI_AI_ID_ARM_NV_SET_BASE				0x0002D000
#define SUSI_AI_ID_ARM_NV_SET_FAN_SPEED			((SusiId_t)(SUSI_AI_ID_ARM_NV_SET_BASE + 0x0))
#define SUSI_AI_ID_ARM_NV_SET_POWER_MODE		((SusiId_t)(SUSI_AI_ID_ARM_NV_SET_BASE + 0x1))

#define SUSI_AI_ID_X86_INTEL_MAX				4
#define SUSI_AI_ID_X86_INTEL_GET_BASE			0x00030000
#define SUSI_AI_ID_X86_INTEL_CPU_USAGE			((SusiId_t)(SUSI_AI_ID_X86_INTEL_GET_BASE + 0x0))
#define SUSI_AI_ID_X86_INTEL_GPU_USAGE			((SusiId_t)(SUSI_AI_ID_X86_INTEL_GET_BASE + 0x1))
#define SUSI_AI_ID_X86_INTEL_CPU_TEMP			((SusiId_t)(SUSI_AI_ID_X86_INTEL_GET_BASE + 0x2))
#define SUSI_AI_ID_X86_INTEL_GPU_TEMP			((SusiId_t)(SUSI_AI_ID_X86_INTEL_GET_BASE + 0x3))

#define SUSI_AI_ID_X86_INTEL_STR_MAX			2
#define SUSI_AI_ID_X86_INTEL_CPU_NAME_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_X86_INTEL_AI + 0x0))
#define SUSI_AI_ID_X86_INTEL_GPU_NAME_STR		((SusiId_t)(SUSI_ID_BASE_GET_NAME_X86_INTEL_AI + 0x1))

#define SUSI_AI_ID_ARM_MTK_MAX				5
#define SUSI_AI_ID_ARM_MTK_BASE				0x00040000
#define SUSI_AI_ID_ARM_MTK_GPU_USAGE			((SusiId_t)(SUSI_AI_ID_ARM_MTK_BASE + 0x0))
#define SUSI_AI_ID_ARM_MTK_CPU_TEMP			((SusiId_t)(SUSI_AI_ID_ARM_MTK_BASE + 0x1))
#define SUSI_AI_ID_ARM_MTK_GPU1_TEMP			((SusiId_t)(SUSI_AI_ID_ARM_MTK_BASE + 0x2))
#define SUSI_AI_ID_ARM_MTK_GPU2_TEMP			((SusiId_t)(SUSI_AI_ID_ARM_MTK_BASE + 0x3))
#define SUSI_AI_ID_ARM_MTK_MEM_INFO			((SusiId_t)(SUSI_AI_ID_ARM_MTK_BASE + 0x4))

#define SUSI_AI_ID_ARM_NXP_MAX				3
#define SUSI_AI_ID_ARM_NXP_BASE				0x00050000
#define SUSI_AI_ID_ARM_NXP_CPU_USAGE			((SusiId_t)(SUSI_AI_ID_ARM_NXP_BASE + 0x0))
#define SUSI_AI_ID_ARM_NXP_CPU_TEMP			((SusiId_t)(SUSI_AI_ID_ARM_NXP_BASE + 0x1))
#define SUSI_AI_ID_ARM_NXP_MEM_INFO			((SusiId_t)(SUSI_AI_ID_ARM_NXP_BASE + 0x2))
/*=============================================================================
// AI
//=============================================================================
*/
/* AI value item IDs */
#define SUSI_ID_AI_SUPPORT_FLAGS			0x00000000

/* Support Flags */
#define SUSI_AI_FLAG_SUPPORT_X86_NV			(1 << 1)
#define SUSI_AI_FLAG_SUPPORT_ARM_NV			(1 << 2)
#define SUSI_AI_FLAG_SUPPORT_DOCKER_IMG		(1 << 3)
#define SUSI_AI_FLAG_SUPPORT_CONTAINER		(1 << 4)
#define SUSI_AI_FLAG_SUPPORT_X86_INTEL		(1 << 5)
#define SUSI_AI_FLAG_SUPPORT_ARM_MTK		(1 << 6)
#define SUSI_AI_FLAG_SUPPORT_ARM_NXP		(1 << 7)

SusiStatus_t SUSI_API SusiAIInitialize(void);
SusiStatus_t SUSI_API SusiAIUninitialize(void);

SusiStatus_t SUSI_API SusiAIGetCaps(
	SusiId_t Id,		/* IN	AI Id */
	uint32_t *pValue	/* OUT	Return Value */
);
SusiStatus_t SUSI_API SusiAISetValue(
	SusiId_t Id,		/* IN	Value Id */
	uint32_t Value      /* IN	Value    */
);
SusiStatus_t SUSI_API SusiAIGetValue(
	SusiId_t Id,		/* IN	Value Id */
	uint32_t *pValue    /* OUT	Return Value */
);
SusiStatus_t SUSI_API SusiAIGetStringA(
	SusiId_t Id,		/* IN		Name Id */
	char *pBuffer,		/* OUT		Destination pBuffer */
	uint32_t *pBufLen	/* INOUT	pBuffer Length */
);

#ifdef __cplusplus
}
#endif
